[category1]
server1 = 'config server 1-1'
server2 = 'config server 1-2'
server3 = 'config server 1-3'
server4 = 'config server 1-4'
server5 = 'config server 1-5'
server6 = 'config server 1-6'
server7 = 'config server 1-7'
server8 = 'config server 1-8'
server9 = 'config server 1-9'
server10 = 'config server 1-10'
server11 = 'config server 1-11'
server12 = 'config server 1-12'
server13 = 'config server 1-13'
server14 = 'config server 1-14'
server15 = 'config server 1-15'

[category2]
server1 = 'config server 2-1'
server2 = 'config server 2-2'
server3 = 'config server 2-3'
server4 = 'config server 2-4'
server5 = 'config server 2-5'
server6 = 'config server 2-6'
server7 = 'config server 2-7'
server8 = 'config server 2-8'
server9 = 'config server 2-9'
server10 = 'config server 2-10'
server11 = 'config server 2-11'
server12 = 'config server 2-12'
server13 = 'config server 2-13'
server14 = 'config server 2-14'
server15 = 'config server 2-15'

[category3]
server1 = 'config server 3-1'
server2 = 'config server 3-2'
server3 = 'config server 3-3'
server4 = 'config server 3-4'
server5 = 'config server 3-5'
server6 = 'config server 3-6'
server7 = 'config server 3-7'
server8 = 'config server 3-8'
server9 = 'config server 3-9'
server10 = 'config server 3-10'
server11 = 'config server 3-11'
server12 = 'config server 3-12'
server13 = 'config server 3-13'
server14 = 'config server 3-14'
server15 = 'config server 3-15'

[category4]
server1 = 'config server 4-1'
server2 = 'config server 4-2'
server3 = 'config server 4-3'
server4 = 'config server 4-4'
server5 = 'config server 4-5'
server6 = 'config server 4-6'
server7 = 'config server 4-7'
server8 = 'config server 4-8'
server9 = 'config server 4-9'
server10 = 'config server 4-10'
server11 = 'config server 4-11'
server12 = 'config server 4-12'
server13 = 'config server 4-13'
server14 = 'config server 4-14'
server15 = 'config server 4-15'

[category5]
server1 = 'config server 5-1'
server2 = 'config server 5-2'
server3 = 'config server 5-3'
server4 = 'config server 5-4'
server5 = 'config server 5-5'
server6 = 'config server 5-6'
server7 = 'config server 5-7'
server8 = 'config server 5-8'
server9 = 'config server 5-9'
server10 = 'config server 5-10'
server11 = 'config server 5-11'
server12 = 'config server 5-12'
server13 = 'config server 5-13'
server14 = 'config server 5-14'
server15 = 'config server 5-15'

[category6]
server1 = 'config server 6-1'
server2 = 'config server 6-2'
server3 = 'config server 6-3'
server4 = 'config server 6-4'
server5 = 'config server 6-5'
server6 = 'config server 6-6'
server7 = 'config server 6-7'
server8 = 'config server 6-8'
server9 = 'config server 6-9'
server10 = 'config server 6-10'
server11 = 'config server 6-11'
server12 = 'config server 6-12'
server13 = 'config server 6-13'
server14 = 'config server 6-14'
server15 = 'config server 6-15'

[category7]
server1 = 'config server 7-1'
server2 = 'config server 7-2'
server3 = 'config server 7-3'
server4 = 'config server 7-4'
server5 = 'config server 7-5'
server6 = 'config server 7-6'
server7 = 'config server 7-7'
server8 = 'config server 7-8'
server9 = 'config server 7-9'
server10 = 'config server 7-10'
server11 = 'config server 7-11'
server12 = 'config server 7-12'
server13 = 'config server 7-13'
server14 = 'config server 7-14'
server15 = 'config server 7-15'

[category8]
server1 = 'config server 8-1'
server2 = 'config server 8-2'
server3 = 'config server 8-3'
server4 = 'config server 8-4'
server5 = 'config server 8-5'
server6 = 'config server 8-6'
server7 = 'config server 8-7'
server8 = 'config server 8-8'
server9 = 'config server 8-9'
server10 = 'config server 8-10'
server11 = 'config server 8-11'
server12 = 'config server 8-12'
server13 = 'config server 8-13'
server14 = 'config server 8-14'
server15 = 'config server 8-15'

[category9]
server1 = 'config server 9-1'
server2 = 'config server 9-2'
server3 = 'config server 9-3'
server4 = 'config server 9-4'
server5 = 'config server 9-5'
server6 = 'config server 9-6'
server7 = 'config server 9-7'
server8 = 'config server 9-8'
server9 = 'config server 9-9'
server10 = 'config server 9-10'
server11 = 'config server 9-11'
server12 = 'config server 9-12'
server13 = 'config server 9-13'
server14 = 'config server 9-14'
server15 = 'config server 9-15'

[category10]
server1 = 'config server 10-1'
server2 = 'config server 10-2'
server3 = 'config server 10-3'
server4 = 'config server 10-4'
server5 = 'config server 10-5'
server6 = 'config server 10-6'
server7 = 'config server 10-7'
server8 = 'config server 10-8'
server9 = 'config server 10-9'
server10 = 'config server 10-10'
server11 = 'config server 10-11'
server12 = 'config server 10-12'
server13 = 'config server 10-13'
server14 = 'config server 10-14'
server15 = 'config server 10-15'

[category11]
server1 = 'config server 11-1'
server2 = 'config server 11-2'
server3 = 'config server 11-3'
server4 = 'config server 11-4'
server5 = 'config server 11-5'
server6 = 'config server 11-6'
server7 = 'config server 11-7'
server8 = 'config server 11-8'
server9 = 'config server 11-9'
server10 = 'config server 11-10'
server11 = 'config server 11-11'
server12 = 'config server 11-12'
server13 = 'config server 11-13'
server14 = 'config server 11-14'
server15 = 'config server 11-15'

[category12]
server1 = 'config server 12-1'
server2 = 'config server 12-2'
server3 = 'config server 12-3'
server4 = 'config server 12-4'
server5 = 'config server 12-5'
server6 = 'config server 12-6'
server7 = 'config server 12-7'
server8 = 'config server 12-8'
server9 = 'config server 12-9'
server10 = 'config server 12-10'
server11 = 'config server 12-11'
server12 = 'config server 12-12'
server13 = 'config server 12-13'
server14 = 'config server 12-14'
server15 = 'config server 12-15'

[category13]
server1 = 'config server 13-1'
server2 = 'config server 13-2'
server3 = 'config server 13-3'
server4 = 'config server 13-4'
server5 = 'config server 13-5'
server6 = 'config server 13-6'
server7 = 'config server 13-7'
server8 = 'config server 13-8'
server9 = 'config server 13-9'
server10 = 'config server 13-10'
server11 = 'config server 13-11'
server12 = 'config server 13-12'
server13 = 'config server 13-13'
server14 = 'config server 13-14'
server15 = 'config server 13-15'

[category14]
server1 = 'config server 14-1'
server2 = 'config server 14-2'
server3 = 'config server 14-3'
server4 = 'config server 14-4'
server5 = 'config server 14-5'
server6 = 'config server 14-6'
server7 = 'config server 14-7'
server8 = 'config server 14-8'
server9 = 'config server 14-9'
server10 = 'config server 14-10'
server11 = 'config server 14-11'
server12 = 'config server 14-12'
server13 = 'config server 14-13'
server14 = 'config server 14-14'
server15 = 'config server 14-15'

[category15]
server1 = 'config server 15-1'
server2 = 'config server 15-2'
server3 = 'config server 15-3'
server4 = 'config server 15-4'
server5 = 'config server 15-5'
server6 = 'config server 15-6'
server7 = 'config server 15-7'
server8 = 'config server 15-8'
server9 = 'config server 15-9'
server10 = 'config server 15-10'
server11 = 'config server 15-11'
server12 = 'config server 15-12'
server13 = 'config server 15-13'
server14 = 'config server 15-14'
server15 = 'config server 15-15'

[category16]
server1 = 'config server 16-1'
server2 = 'config server 16-2'
server3 = 'config server 16-3'
server4 = 'config server 16-4'
server5 = 'config server 16-5'
server6 = 'config server 16-6'
server7 = 'config server 16-7'
server8 = 'config server 16-8'
server9 = 'config server 16-9'
server10 = 'config server 16-10'
server11 = 'config server 16-11'
server12 = 'config server 16-12'
server13 = 'config server 16-13'
server14 = 'config server 16-14'
server15 = 'config server 16-15'

[category17]
server1 = 'config server 17-1'
server2 = 'config server 17-2'
server3 = 'config server 17-3'
server4 = 'config server 17-4'
server5 = 'config server 17-5'
server6 = 'config server 17-6'
server7 = 'config server 17-7'
server8 = 'config server 17-8'
server9 = 'config server 17-9'
server10 = 'config server 17-10'
server11 = 'config server 17-11'
server12 = 'config server 17-12'
server13 = 'config server 17-13'
server14 = 'config server 17-14'
server15 = 'config server 17-15'

[category18]
server1 = 'config server 18-1'
server2 = 'config server 18-2'
server3 = 'config server 18-3'
server4 = 'config server 18-4'
server5 = 'config server 18-5'
server6 = 'config server 18-6'
server7 = 'config server 18-7'
server8 = 'config server 18-8'
server9 = 'config server 18-9'
server10 = 'config server 18-10'
server11 = 'config server 18-11'
server12 = 'config server 18-12'
server13 = 'config server 18-13'
server14 = 'config server 18-14'
server15 = 'config server 18-15'

[category19]
server1 = 'config server 19-1'
server2 = 'config server 19-2'
server3 = 'config server 19-3'
server4 = 'config server 19-4'
server5 = 'config server 19-5'
server6 = 'config server 19-6'
server7 = 'config server 19-7'
server8 = 'config server 19-8'
server9 = 'config server 19-9'
server10 = 'config server 19-10'
server11 = 'config server 19-11'
server12 = 'config server 19-12'
server13 = 'config server 19-13'
server14 = 'config server 19-14'
server15 = 'config server 19-15'

[category20]
server1 = 'config server 20-1'
server2 = 'config server 20-2'
server3 = 'config server 20-3'
server4 = 'config server 20-4'
server5 = 'config server 20-5'
server6 = 'config server 20-6'
server7 = 'config server 20-7'
server8 = 'config server 20-8'
server9 = 'config server 20-9'
server10 = 'config server 20-10'
server11 = 'config server 20-11'
server12 = 'config server 20-12'
server13 = 'config server 20-13'
server14 = 'config server 20-14'
server15 = 'config server 20-15'

[category21]
server1 = 'config server 21-1'
server2 = 'config server 21-2'
server3 = 'config server 21-3'
server4 = 'config server 21-4'
server5 = 'config server 21-5'
server6 = 'config server 21-6'
server7 = 'config server 21-7'
server8 = 'config server 21-8'
server9 = 'config server 21-9'
server10 = 'config server 21-10'
server11 = 'config server 21-11'
server12 = 'config server 21-12'
server13 = 'config server 21-13'
server14 = 'config server 21-14'
server15 = 'config server 21-15'

[category22]
server1 = 'config server 22-1'
server2 = 'config server 22-2'
server3 = 'config server 22-3'
server4 = 'config server 22-4'
server5 = 'config server 22-5'
server6 = 'config server 22-6'
server7 = 'config server 22-7'
server8 = 'config server 22-8'
server9 = 'config server 22-9'
server10 = 'config server 22-10'
server11 = 'config server 22-11'
server12 = 'config server 22-12'
server13 = 'config server 22-13'
server14 = 'config server 22-14'
server15 = 'config server 22-15'

[category23]
server1 = 'config server 23-1'
server2 = 'config server 23-2'
server3 = 'config server 23-3'
server4 = 'config server 23-4'
server5 = 'config server 23-5'
server6 = 'config server 23-6'
server7 = 'config server 23-7'
server8 = 'config server 23-8'
server9 = 'config server 23-9'
server10 = 'config server 23-10'
server11 = 'config server 23-11'
server12 = 'config server 23-12'
server13 = 'config server 23-13'
server14 = 'config server 23-14'
server15 = 'config server 23-15'

[category24]
server1 = 'config server 24-1'
server2 = 'config server 24-2'
server3 = 'config server 24-3'
server4 = 'config server 24-4'
server5 = 'config server 24-5'
server6 = 'config server 24-6'
server7 = 'config server 24-7'
server8 = 'config server 24-8'
server9 = 'config server 24-9'
server10 = 'config server 24-10'
server11 = 'config server 24-11'
server12 = 'config server 24-12'
server13 = 'config server 24-13'
server14 = 'config server 24-14'
server15 = 'config server 24-15'

[category25]
server1 = 'config server 25-1'
server2 = 'config server 25-2'
server3 = 'config server 25-3'
server4 = 'config server 25-4'
server5 = 'config server 25-5'
server6 = 'config server 25-6'
server7 = 'config server 25-7'
server8 = 'config server 25-8'
server9 = 'config server 25-9'
server10 = 'config server 25-10'
server11 = 'config server 25-11'
server12 = 'config server 25-12'
server13 = 'config server 25-13'
server14 = 'config server 25-14'
server15 = 'config server 25-15'

[category26]
server1 = 'config server 26-1'
server2 = 'config server 26-2'
server3 = 'config server 26-3'
server4 = 'config server 26-4'
server5 = 'config server 26-5'
server6 = 'config server 26-6'
server7 = 'config server 26-7'
server8 = 'config server 26-8'
server9 = 'config server 26-9'
server10 = 'config server 26-10'
server11 = 'config server 26-11'
server12 = 'config server 26-12'
server13 = 'config server 26-13'
server14 = 'config server 26-14'
server15 = 'config server 26-15'

[category27]
server1 = 'config server 27-1'
server2 = 'config server 27-2'
server3 = 'config server 27-3'
server4 = 'config server 27-4'
server5 = 'config server 27-5'
server6 = 'config server 27-6'
server7 = 'config server 27-7'
server8 = 'config server 27-8'
server9 = 'config server 27-9'
server10 = 'config server 27-10'
server11 = 'config server 27-11'
server12 = 'config server 27-12'
server13 = 'config server 27-13'
server14 = 'config server 27-14'
server15 = 'config server 27-15'

[category28]
server1 = 'config server 28-1'
server2 = 'config server 28-2'
server3 = 'config server 28-3'
server4 = 'config server 28-4'
server5 = 'config server 28-5'
server6 = 'config server 28-6'
server7 = 'config server 28-7'
server8 = 'config server 28-8'
server9 = 'config server 28-9'
server10 = 'config server 28-10'
server11 = 'config server 28-11'
server12 = 'config server 28-12'
server13 = 'config server 28-13'
server14 = 'config server 28-14'
server15 = 'config server 28-15'

[category29]
server1 = 'config server 29-1'
server2 = 'config server 29-2'
server3 = 'config server 29-3'
server4 = 'config server 29-4'
server5 = 'config server 29-5'
server6 = 'config server 29-6'
server7 = 'config server 29-7'
server8 = 'config server 29-8'
server9 = 'config server 29-9'
server10 = 'config server 29-10'
server11 = 'config server 29-11'
server12 = 'config server 29-12'
server13 = 'config server 29-13'
server14 = 'config server 29-14'
server15 = 'config server 29-15'

[category30]
server1 = 'config server 30-1'
server2 = 'config server 30-2'
server3 = 'config server 30-3'
server4 = 'config server 30-4'
server5 = 'config server 30-5'
server6 = 'config server 30-6'
server7 = 'config server 30-7'
server8 = 'config server 30-8'
server9 = 'config server 30-9'
server10 = 'config server 30-10'
server11 = 'config server 30-11'
server12 = 'config server 30-12'
server13 = 'config server 30-13'
server14 = 'config server 30-14'
server15 = 'config server 30-15'
