[servers]
    [servers.alpha]
    ip = ["10.0.0.1"]
    dc = ["eqdc10"]
    server1 = ['config example 1-1']
    server2 = ['config', 'example', '1-2']
        [servers.alpha.another]
            [servers.alpha.another.another]
            server6 = ['config', 'example', '2-6']
            server7 = ['config example 2-7']
            server8 = ['config', 'example', '2-8']
                [servers.alpha.another.another.anotheragain]
                server6 = ['config', 'example', '2-6']
                server7 = ['config example 2-7']
                server8 = ['config', 'example', '2-8']


    [servers.beta]
    ip = ["10.0.0.2"]
    dc = ["eqdc10"]
    server3 = ['config example 1-3']



[failingSection]
test = 'this should not be loaded by the soft'

[RealCommand]
opening-iTerm = ['open -a iTerm']


[commands-manager-configuration]
pixels_per_point = 1.0                  # Defines interface size
indentation_amplifier = 16.0            # Defines differences between sections and nested sections
rgb_initial_value = [232, 232, 232]     # Base rgb values of the interface
