[category1]
server1 = ['config example 1-1']
server2 = ['config', 'example', '1-2']
server3 = ['config example 1-3']
server4 = ['config', 'example', '1-4']
server5 = ['config example 1-5']
server6 = ['config', 'example', '1-6']
server7 = ['config example 1-7']
server8 = ['config', 'example', '1-8']
server9 = ['config example 1-9']
server10 = ['config', 'example', '1-10']
server11 = ['config example 1-11']
server12 = ['config', 'example', '1-12']
server13 = ['config example 1-13']
server14 = ['config', 'example', '1-14']
server15 = ['config example 1-15']

[category2]
server1 = ['config example 2-1']
server2 = ['config', 'example', '2-2']
server3 = ['config example 2-3']
server4 = ['config', 'example', '2-4']
server5 = ['config example 2-5']
server6 = ['config', 'example', '2-6']
server7 = ['config example 2-7']
server8 = ['config', 'example', '2-8']
server9 = ['config example 2-9']
server10 = ['config', 'example', '2-10']
server11 = ['config example 2-11']
server12 = ['config', 'example', '2-12']
server13 = ['config example 2-13']
server14 = ['config', 'example', '2-14']
server15 = ['config example 2-15']

[category3]
server1 = ['config example 3-1']
server2 = ['config', 'example', '3-2']
server3 = ['config example 3-3']
server4 = ['config', 'example', '3-4']
server5 = ['config example 3-5']
server6 = ['config', 'example', '3-6']
server7 = ['config example 3-7']
server8 = ['config', 'example', '3-8']
server9 = ['config example 3-9']
server10 = ['config', 'example', '3-10']
server11 = ['config example 3-11']
server12 = ['config', 'example', '3-12']
server13 = ['config example 3-13']
server14 = ['config', 'example', '3-14']
server15 = ['config example 3-15']

[category4]
server1 = ['config example 4-1']
server2 = ['config', 'example', '4-2']
server3 = ['config example 4-3']
server4 = ['config', 'example', '4-4']
server5 = ['config example 4-5']
server6 = ['config', 'example', '4-6']
server7 = ['config example 4-7']
server8 = ['config', 'example', '4-8']
server9 = ['config example 4-9']
server10 = ['config', 'example', '4-10']
server11 = ['config example 4-11']
server12 = ['config', 'example', '4-12']
server13 = ['config example 4-13']
server14 = ['config', 'example', '4-14']
server15 = ['config example 4-15']

[category5]
server1 = ['config example 5-1']
server2 = ['config', 'example', '5-2']
server3 = ['config example 5-3']
server4 = ['config', 'example', '5-4']
server5 = ['config example 5-5']
server6 = ['config', 'example', '5-6']
server7 = ['config example 5-7']
server8 = ['config', 'example', '5-8']
server9 = ['config example 5-9']
server10 = ['config', 'example', '5-10']
server11 = ['config example 5-11']
server12 = ['config', 'example', '5-12']
server13 = ['config example 5-13']
server14 = ['config', 'example', '5-14']
server15 = ['config example 5-15']

[category6]
server1 = ['config example 6-1']
server2 = ['config', 'example', '6-2']
server3 = ['config example 6-3']
server4 = ['config', 'example', '6-4']
server5 = ['config example 6-5']
server6 = ['config', 'example', '6-6']
server7 = ['config example 6-7']
server8 = ['config', 'example', '6-8']
server9 = ['config example 6-9']
server10 = ['config', 'example', '6-10']
server11 = ['config example 6-11']
server12 = ['config', 'example', '6-12']
server13 = ['config example 6-13']
server14 = ['config', 'example', '6-14']
server15 = ['config example 6-15']

[category7]
server1 = ['config example 7-1']
server2 = ['config', 'example', '7-2']
server3 = ['config example 7-3']
server4 = ['config', 'example', '7-4']
server5 = ['config example 7-5']
server6 = ['config', 'example', '7-6']
server7 = ['config example 7-7']
server8 = ['config', 'example', '7-8']
server9 = ['config example 7-9']
server10 = ['config', 'example', '7-10']
server11 = ['config example 7-11']
server12 = ['config', 'example', '7-12']
server13 = ['config example 7-13']
server14 = ['config', 'example', '7-14']
server15 = ['config example 7-15']

[category8]
server1 = ['config example 8-1']
server2 = ['config', 'example', '8-2']
server3 = ['config example 8-3']
server4 = ['config', 'example', '8-4']
server5 = ['config example 8-5']
server6 = ['config', 'example', '8-6']
server7 = ['config example 8-7']
server8 = ['config', 'example', '8-8']
server9 = ['config example 8-9']
server10 = ['config', 'example', '8-10']
server11 = ['config example 8-11']
server12 = ['config', 'example', '8-12']
server13 = ['config example 8-13']
server14 = ['config', 'example', '8-14']
server15 = ['config example 8-15']

[category9]
server1 = ['config example 9-1']
server2 = ['config', 'example', '9-2']
server3 = ['config example 9-3']
server4 = ['config', 'example', '9-4']
server5 = ['config example 9-5']
server6 = ['config', 'example', '9-6']
server7 = ['config example 9-7']
server8 = ['config', 'example', '9-8']
server9 = ['config example 9-9']
server10 = ['config', 'example', '9-10']
server11 = ['config example 9-11']
server12 = ['config', 'example', '9-12']
server13 = ['config example 9-13']
server14 = ['config', 'example', '9-14']
server15 = ['config example 9-15']

[category10]
server1 = ['config example 10-1']
server2 = ['config', 'example', '10-2']
server3 = ['config example 10-3']
server4 = ['config', 'example', '10-4']
server5 = ['config example 10-5']
server6 = ['config', 'example', '10-6']
server7 = ['config example 10-7']
server8 = ['config', 'example', '10-8']
server9 = ['config example 10-9']
server10 = ['config', 'example', '10-10']
server11 = ['config example 10-11']
server12 = ['config', 'example', '10-12']
server13 = ['config example 10-13']
server14 = ['config', 'example', '10-14']
server15 = ['config example 10-15']

[category11]
server1 = ['config example 11-1']
server2 = ['config', 'example', '11-2']
server3 = ['config example 11-3']
server4 = ['config', 'example', '11-4']
server5 = ['config example 11-5']
server6 = ['config', 'example', '11-6']
server7 = ['config example 11-7']
server8 = ['config', 'example', '11-8']
server9 = ['config example 11-9']
server10 = ['config', 'example', '11-10']
server11 = ['config example 11-11']
server12 = ['config', 'example', '11-12']
server13 = ['config example 11-13']
server14 = ['config', 'example', '11-14']
server15 = ['config example 11-15']

[category12]
server1 = ['config example 12-1']
server2 = ['config', 'example', '12-2']
server3 = ['config example 12-3']
server4 = ['config', 'example', '12-4']
server5 = ['config example 12-5']
server6 = ['config', 'example', '12-6']
server7 = ['config example 12-7']
server8 = ['config', 'example', '12-8']
server9 = ['config example 12-9']
server10 = ['config', 'example', '12-10']
server11 = ['config example 12-11']
server12 = ['config', 'example', '12-12']
server13 = ['config example 12-13']
server14 = ['config', 'example', '12-14']
server15 = ['config example 12-15']

[category13]
server1 = ['config example 13-1']
server2 = ['config', 'example', '13-2']
server3 = ['config example 13-3']
server4 = ['config', 'example', '13-4']
server5 = ['config example 13-5']
server6 = ['config', 'example', '13-6']
server7 = ['config example 13-7']
server8 = ['config', 'example', '13-8']
server9 = ['config example 13-9']
server10 = ['config', 'example', '13-10']
server11 = ['config example 13-11']
server12 = ['config', 'example', '13-12']
server13 = ['config example 13-13']
server14 = ['config', 'example', '13-14']
server15 = ['config example 13-15']

[category14]
server1 = ['config example 14-1']
server2 = ['config', 'example', '14-2']
server3 = ['config example 14-3']
server4 = ['config', 'example', '14-4']
server5 = ['config example 14-5']
server6 = ['config', 'example', '14-6']
server7 = ['config example 14-7']
server8 = ['config', 'example', '14-8']
server9 = ['config example 14-9']
server10 = ['config', 'example', '14-10']
server11 = ['config example 14-11']
server12 = ['config', 'example', '14-12']
server13 = ['config example 14-13']
server14 = ['config', 'example', '14-14']
server15 = ['config example 14-15']

[category15]
server1 = ['config example 15-1']
server2 = ['config', 'example', '15-2']
server3 = ['config example 15-3']
server4 = ['config', 'example', '15-4']
server5 = ['config example 15-5']
server6 = ['config', 'example', '15-6']
server7 = ['config example 15-7']
server8 = ['config', 'example', '15-8']
server9 = ['config example 15-9']
server10 = ['config', 'example', '15-10']
server11 = ['config example 15-11']
server12 = ['config', 'example', '15-12']
server13 = ['config example 15-13']
server14 = ['config', 'example', '15-14']
server15 = ['config example 15-15']

[category16]
server1 = ['config example 16-1']
server2 = ['config', 'example', '16-2']
server3 = ['config example 16-3']
server4 = ['config', 'example', '16-4']
server5 = ['config example 16-5']
server6 = ['config', 'example', '16-6']
server7 = ['config example 16-7']
server8 = ['config', 'example', '16-8']
server9 = ['config example 16-9']
server10 = ['config', 'example', '16-10']
server11 = ['config example 16-11']
server12 = ['config', 'example', '16-12']
server13 = ['config example 16-13']
server14 = ['config', 'example', '16-14']
server15 = ['config example 16-15']

[category17]
server1 = ['config example 17-1']
server2 = ['config', 'example', '17-2']
server3 = ['config example 17-3']
server4 = ['config', 'example', '17-4']
server5 = ['config example 17-5']
server6 = ['config', 'example', '17-6']
server7 = ['config example 17-7']
server8 = ['config', 'example', '17-8']
server9 = ['config example 17-9']
server10 = ['config', 'example', '17-10']
server11 = ['config example 17-11']
server12 = ['config', 'example', '17-12']
server13 = ['config example 17-13']
server14 = ['config', 'example', '17-14']
server15 = ['config example 17-15']

[category18]
server1 = ['config example 18-1']
server2 = ['config', 'example', '18-2']
server3 = ['config example 18-3']
server4 = ['config', 'example', '18-4']
server5 = ['config example 18-5']
server6 = ['config', 'example', '18-6']
server7 = ['config example 18-7']
server8 = ['config', 'example', '18-8']
server9 = ['config example 18-9']
server10 = ['config', 'example', '18-10']
server11 = ['config example 18-11']
server12 = ['config', 'example', '18-12']
server13 = ['config example 18-13']
server14 = ['config', 'example', '18-14']
server15 = ['config example 18-15']

[category19]
server1 = ['config example 19-1']
server2 = ['config', 'example', '19-2']
server3 = ['config example 19-3']
server4 = ['config', 'example', '19-4']
server5 = ['config example 19-5']
server6 = ['config', 'example', '19-6']
server7 = ['config example 19-7']
server8 = ['config', 'example', '19-8']
server9 = ['config example 19-9']
server10 = ['config', 'example', '19-10']
server11 = ['config example 19-11']
server12 = ['config', 'example', '19-12']
server13 = ['config example 19-13']
server14 = ['config', 'example', '19-14']
server15 = ['config example 19-15']

[category20]
server1 = ['config example 20-1']
server2 = ['config', 'example', '20-2']
server3 = ['config example 20-3']
server4 = ['config', 'example', '20-4']
server5 = ['config example 20-5']
server6 = ['config', 'example', '20-6']
server7 = ['config example 20-7']
server8 = ['config', 'example', '20-8']
server9 = ['config example 20-9']
server10 = ['config', 'example', '20-10']
server11 = ['config example 20-11']
server12 = ['config', 'example', '20-12']
server13 = ['config example 20-13']
server14 = ['config', 'example', '20-14']
server15 = ['config example 20-15']

[category21]
server1 = ['config example 21-1']
server2 = ['config', 'example', '21-2']
server3 = ['config example 21-3']
server4 = ['config', 'example', '21-4']
server5 = ['config example 21-5']
server6 = ['config', 'example', '21-6']
server7 = ['config example 21-7']
server8 = ['config', 'example', '21-8']
server9 = ['config example 21-9']
server10 = ['config', 'example', '21-10']
server11 = ['config example 21-11']
server12 = ['config', 'example', '21-12']
server13 = ['config example 21-13']
server14 = ['config', 'example', '21-14']
server15 = ['config example 21-15']

[category22]
server1 = ['config example 22-1']
server2 = ['config', 'example', '22-2']
server3 = ['config example 22-3']
server4 = ['config', 'example', '22-4']
server5 = ['config example 22-5']
server6 = ['config', 'example', '22-6']
server7 = ['config example 22-7']
server8 = ['config', 'example', '22-8']
server9 = ['config example 22-9']
server10 = ['config', 'example', '22-10']
server11 = ['config example 22-11']
server12 = ['config', 'example', '22-12']
server13 = ['config example 22-13']
server14 = ['config', 'example', '22-14']
server15 = ['config example 22-15']

[category23]
server1 = ['config example 23-1']
server2 = ['config', 'example', '23-2']
server3 = ['config example 23-3']
server4 = ['config', 'example', '23-4']
server5 = ['config example 23-5']
server6 = ['config', 'example', '23-6']
server7 = ['config example 23-7']
server8 = ['config', 'example', '23-8']
server9 = ['config example 23-9']
server10 = ['config', 'example', '23-10']
server11 = ['config example 23-11']
server12 = ['config', 'example', '23-12']
server13 = ['config example 23-13']
server14 = ['config', 'example', '23-14']
server15 = ['config example 23-15']

[category24]
server1 = ['config example 24-1']
server2 = ['config', 'example', '24-2']
server3 = ['config example 24-3']
server4 = ['config', 'example', '24-4']
server5 = ['config example 24-5']
server6 = ['config', 'example', '24-6']
server7 = ['config example 24-7']
server8 = ['config', 'example', '24-8']
server9 = ['config example 24-9']
server10 = ['config', 'example', '24-10']
server11 = ['config example 24-11']
server12 = ['config', 'example', '24-12']
server13 = ['config example 24-13']
server14 = ['config', 'example', '24-14']
server15 = ['config example 24-15']

[category25]
server1 = ['config example 25-1']
server2 = ['config', 'example', '25-2']
server3 = ['config example 25-3']
server4 = ['config', 'example', '25-4']
server5 = ['config example 25-5']
server6 = ['config', 'example', '25-6']
server7 = ['config example 25-7']
server8 = ['config', 'example', '25-8']
server9 = ['config example 25-9']
server10 = ['config', 'example', '25-10']
server11 = ['config example 25-11']
server12 = ['config', 'example', '25-12']
server13 = ['config example 25-13']
server14 = ['config', 'example', '25-14']
server15 = ['config example 25-15']

[category26]
server1 = ['config example 26-1']
server2 = ['config', 'example', '26-2']
server3 = ['config example 26-3']
server4 = ['config', 'example', '26-4']
server5 = ['config example 26-5']
server6 = ['config', 'example', '26-6']
server7 = ['config example 26-7']
server8 = ['config', 'example', '26-8']
server9 = ['config example 26-9']
server10 = ['config', 'example', '26-10']
server11 = ['config example 26-11']
server12 = ['config', 'example', '26-12']
server13 = ['config example 26-13']
server14 = ['config', 'example', '26-14']
server15 = ['config example 26-15']

[category27]
server1 = ['config example 27-1']
server2 = ['config', 'example', '27-2']
server3 = ['config example 27-3']
server4 = ['config', 'example', '27-4']
server5 = ['config example 27-5']
server6 = ['config', 'example', '27-6']
server7 = ['config example 27-7']
server8 = ['config', 'example', '27-8']
server9 = ['config example 27-9']
server10 = ['config', 'example', '27-10']
server11 = ['config example 27-11']
server12 = ['config', 'example', '27-12']
server13 = ['config example 27-13']
server14 = ['config', 'example', '27-14']
server15 = ['config example 27-15']

[category28]
server1 = ['config example 28-1']
server2 = ['config', 'example', '28-2']
server3 = ['config example 28-3']
server4 = ['config', 'example', '28-4']
server5 = ['config example 28-5']
server6 = ['config', 'example', '28-6']
server7 = ['config example 28-7']
server8 = ['config', 'example', '28-8']
server9 = ['config example 28-9']
server10 = ['config', 'example', '28-10']
server11 = ['config example 28-11']
server12 = ['config', 'example', '28-12']
server13 = ['config example 28-13']
server14 = ['config', 'example', '28-14']
server15 = ['config example 28-15']

[category29]
server1 = ['config example 29-1']
server2 = ['config', 'example', '29-2']
server3 = ['config example 29-3']
server4 = ['config', 'example', '29-4']
server5 = ['config example 29-5']
server6 = ['config', 'example', '29-6']
server7 = ['config example 29-7']
server8 = ['config', 'example', '29-8']
server9 = ['config example 29-9']
server10 = ['config', 'example', '29-10']
server11 = ['config example 29-11']
server12 = ['config', 'example', '29-12']
server13 = ['config example 29-13']
server14 = ['config', 'example', '29-14']
server15 = ['config example 29-15']

[category30]
server1 = ['config example 30-1']
server2 = ['config', 'example', '30-2']
server3 = ['config example 30-3']
server4 = ['config', 'example', '30-4']
server5 = ['config example 30-5']
server6 = ['config', 'example', '30-6']
server7 = ['config example 30-7']
server8 = ['config', 'example', '30-8']
server9 = ['config example 30-9']
server10 = ['config', 'example', '30-10']
server11 = ['config example 30-11']
server12 = ['config', 'example', '30-12']
server13 = ['config example 30-13']
server14 = ['config', 'example', '30-14']
server15 = ['config example 30-15']


[failingSection]
test = 'huhuhu'

[RealCommand]
opening-iTerm = ['open -a iTerm']
